spring:
  application:
    name: adm
  thymeleaf:
    cache: false
    mode: HTML5
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
server:
  port: 9000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript