spring:
  application:
    name: adm
  thymeleaf:
    cache: false
    mode: HTML
server:
  port: 9000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript