#public config file
spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${random.int}
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
server:
  port: 0
management:
  security:
    enabled: false