#public config file
spring:
  boot:
    admin:
      url: http://localhost:8400
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${random.int}
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
server:
  port: 0
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true
# 设置连接超时时间
ribbon:
  ConnectTimeout: 1000
# 设置读取超时时间
  ReadTimeout: 3000
# 对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
# 切换实例的重试次数
  MaxAutoRetriesNextServer: 2
# 对当前实例的重试次数
  MaxAutoRetries: 1
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #熔断超时时间
            timeoutInMilliseconds: 10000
info:
  version: 1.0-SNAPSHOT